# Makefile.dep created Wed May  8 11:36:22 PDT 2019
protocol.o: protocol.cpp protocol.h sockets.h
sockets.o: sockets.cpp sockets.h
cix.o: cix.cpp protocol.h sockets.h logstream.h
cixd.o: cixd.cpp protocol.h sockets.h logstream.h
